# Extended XALEN type surface for the GoToValhalla Tarot fork.
# The validated upstream/advanced API is preserved in xalen_base.pyi and
# re-exported here; declarations below cover fork enrichment APIs.

from typing import Any, Dict, List
from xalen_base import *  # noqa: F401,F403


def ashtakavarga(planet_signs: List[int]) -> Dict[str, Any]: ...
def ashtottari_dasha(moon_sidereal_deg: float, birth_jd: float) -> List[Dict[str, Any]]: ...
def yogini_dasha(moon_sidereal_deg: float, birth_jd: float) -> List[Dict[str, Any]]: ...
def ashtakoota(boy_nakshatra_index: int, girl_nakshatra_index: int, boy_rashi_index: int, girl_rashi_index: int) -> Dict[str, Any]: ...
def shadbala(planet: str, lon_deg: float, house: int, speed: float, jd: float, sun_lon: float, moon_lon: float, day_fraction: float, all_planets: List[tuple[str, float, float]]) -> Dict[str, Any]: ...
def mangal_dosha(mars_house_from_lagna: int, mars_house_from_moon: int, mars_house_from_venus: int, mars_nakshatra_index: int, jupiter_aspects_mars: bool = ..., mars_in_own_sign: bool = ..., mars_in_exaltation: bool = ...) -> Dict[str, Any]: ...
def kaal_sarpa_dosha(rahu_house: int, ketu_house: int, planet_houses: List[int]) -> Dict[str, Any]: ...
def pitra_dosha(sun_house: int, saturn_house: int, rahu_house: int, ninth_lord_house: int, ninth_lord_debilitated: bool) -> Dict[str, Any]: ...
def pancha_mahapurusha_yoga(planet: str, rashi_index: int, house: int) -> Dict[str, Any] | None: ...
def gajakesari_yoga(jupiter_house: int, moon_house: int) -> Dict[str, Any] | None: ...
def budhaditya_yoga(sun_house: int, mercury_house: int) -> Dict[str, Any] | None: ...
def vipreeta_raja_yoga(lord_6_house: int, lord_8_house: int, lord_12_house: int) -> List[Dict[str, Any]]: ...
def kemadruma_yoga(moon_house: int, supporting_planet_houses: List[int]) -> Dict[str, Any] | None: ...

def fixed_star(name: str, year: float = ...) -> Dict[str, Any] | None: ...
def yogatara(nakshatra_index: int, year: float = ...) -> Dict[str, Any] | None: ...
def fixed_star_catalog_info() -> Dict[str, Any]: ...
def render_chart_svg(style: str, planet_positions: List[tuple[str, int, float]], house_cusps_deg: List[float], ascendant_sign_index: int, ayanamsa_deg: float = ...) -> str: ...

# Advanced Western
def annual_profection(natal_asc_sign: int, age: int) -> Dict[str, Any]: ...
def zodiacal_releasing(lot_sign: int, birth_jd: float, levels: int = ...) -> List[Dict[str, Any]]: ...
def solar_arc_directions(natal_sun: float, progressed_sun: float, natal_positions: List[tuple[str, float]]) -> Dict[str, Any]: ...
def declination(lon_deg: float, lat_deg: float, obliquity_deg: float) -> float: ...
def declination_aspects(positions: List[tuple[str, float, float]], obliquity_deg: float = ..., orb_deg: float = ...) -> List[Dict[str, Any]]: ...
def essential_dignity(planet: str, sign_index: int, degree_in_sign: float) -> Dict[str, Any]: ...
def arabic_lots(sun: float, moon: float, mercury: float, venus: float, mars: float, jupiter: float, saturn: float, asc: float, mc: float, is_day: bool) -> List[Dict[str, Any]]: ...
def composite_midpoints(chart_a: List[tuple[str, float]], chart_b: List[tuple[str, float]]) -> List[Dict[str, Any]]: ...
def davison_midpoint(jd_a: float, lat_a: float, lon_a: float, jd_b: float, lat_b: float, lon_b: float) -> Dict[str, Any]: ...
def moon_quality(moon_lon: float, moon_speed: float, planets: List[tuple[str, float, float]]) -> Dict[str, Any]: ...
def sign_ingresses(body_id: int, jd_start: float, jd_end: float, step_days: float = ...) -> List[Dict[str, Any]]: ...
def stations(body_id: int, jd_start: float, jd_end: float, step_days: float = ...) -> List[Dict[str, Any]]: ...
def solar_eclipses(jd_start: float, jd_end: float) -> List[Dict[str, Any]]: ...
def lunar_eclipses(jd_start: float, jd_end: float) -> List[Dict[str, Any]]: ...
